{% set name = "semimap" %}
{% set version = "1.0.0" %}
{% set organization = "QuantStack" %}
{% set sha256 = "77534da5e5c8c582945210a5665c9f711e323e17853bc92fa45601c410f42611" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ organization }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - bash {{ RECIPE_DIR }}/run_test.sh  # [not win]
    - {{ RECIPE_DIR }}/run_test.bat  # [win]

about:
  home: https://github.com/{{ organization }}/{{ name }}/
  summary: 'A semi compile-/run-time associative map container with compile-time lookup and run-time storage'
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/{{ organization }}/{{ name }}/

extra:
  recipe-maintainers:
    - jjerphan
    - DerThorsten
    - JohanMabille
